'use client';
import { useEffect, useState } from 'react';
import { apiFetch } from '../lib/api';

type Analysis={documentType:'contract'|'invoice'|'report'|'other';language:string;summary:string;riskLevel:'low'|'medium'|'high';flags:string[]};
type Document={id:string;originalFilename:string;status:string;createdAt:string;updatedAt:string;failureReason?:string;analysis:Analysis|null};
export const DocumentReview=({id}:{id:string})=>{const [doc,setDoc]=useState<Document|null>(null),[form,setForm]=useState<Analysis|null>(null),[dirty,setDirty]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{const r=await apiFetch(`/documents/${id}`);const b=await r.json();if(!r.ok)throw new Error(b.error?.message);setDoc(b.document);setForm(b.document.analysis);setDirty(false)}; useEffect(()=>{load().catch(e=>setMessage(e.message))},[id]);
 const save=async()=>{if(!form)return;setMessage('');const r=await apiFetch(`/documents/${id}/analysis`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const b=await r.json();if(!r.ok){setMessage(b.error?.message);return}setForm(b.analysis);setDirty(false);setMessage('Saved');await load()};
 const approve=async()=>{const r=await apiFetch(`/documents/${id}/approve`,{method:'POST'});const b=await r.json();if(!r.ok){setMessage(b.error?.message);return}setMessage('Approved');await load()};
 if(!doc)return <p>{message||'Loading document…'}</p>; const editable=doc.status==='REVIEW_REQUIRED'&&form; const change=(key:keyof Analysis,value:unknown)=>{if(form){setForm({...form,[key]:value});setDirty(true)}};
 return <main><h1>{doc.originalFilename}</h1><p>Status: <strong>{doc.status}</strong></p><p>Created: {doc.createdAt}</p><p>Updated: {doc.updatedAt}</p>{doc.status==='FAILED'?<p>{doc.failureReason||'Processing failed.'}</p>:null}{!doc.analysis?<p>Analysis is not ready yet.</p>:editable?<section><label>Document Type<select value={form.documentType} onChange={e=>change('documentType',e.target.value)}>{['contract','invoice','report','other'].map(x=><option key={x}>{x}</option>)}</select></label><label>Language<input value={form.language} onChange={e=>change('language',e.target.value)}/></label><label>Summary<textarea value={form.summary} onChange={e=>change('summary',e.target.value)}/></label><label>Risk Level<select value={form.riskLevel} onChange={e=>change('riskLevel',e.target.value)}>{['low','medium','high'].map(x=><option key={x}>{x}</option>)}</select></label><label>Flags<textarea value={form.flags.join('\n')} onChange={e=>change('flags',e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))}/></label><button onClick={save}>Save changes</button><button onClick={approve} disabled={dirty}>Approve document</button>{dirty?<p>Save changes before approving.</p>:null}</section>:<section><p>Document Type: {doc.analysis.documentType}</p><p>Language: {doc.analysis.language}</p><p>Summary: {doc.analysis.summary}</p><p>Risk Level: {doc.analysis.riskLevel}</p><p>Flags: {doc.analysis.flags.join(', ')||'None'}</p>{doc.status==='APPROVED'?<p>APPROVED</p>:null}</section>}<p>{message}</p></main>};
